### ISSUE TITLE
Streaming Logs

### ISSUE THREAD

**Issue by bencevans** [webcast-io/redstone#7]
When executing long commands with progress updates/output it would be lovely to see that streamed through (especially to the console when using `grunt-redstone`).

**Comment by paulbjensen** [comment]
Agreed. The way that the ssh lib we're using works doesn't persist a session between commands, hence the constant use of cd before our deploy commands, so we need to take a look at other ssh libraries, or even write our own to support this.

**Comment by bencevans** [comment]
Cool, I can recommend https://github.com/mscdex/ssh2, although we'd have to write the parser for command output etc. I believe as all it does from what I remember is open a persistent stream and provide you with a node stream interface.

**Comment by bencevans** [comment]
Something along the lines of Heroku's deploy.
